spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/institute}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

server:
  port: 8080
